### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by hiccups1980** [jc9108/ttv-favorites#4] opened 2022-11-10 19:18 UTC
It does not work for me. I press the star button next to the follow button. When I refresh the website, the star is empty again. As if I had never pressed there. Also, the favorite streamers do not show up on the left side of the list.

That being said, Twitch has now introduced a sorting option. You can sort between "recommended" and "much -> less".

Or is it because of Frankerface that I have installed?

I would love to get it running. I would be happy  if I get help.

**Comment by IZeeRocks** [comment] 2022-11-10 21:53
I am having the exact same issue

**Comment by jc9108** [comment] 2022-11-11 00:33
> That being said, Twitch has now introduced a sorting option. You can sort between "recommended" and "much -> less".

yeah this ui update broke it

fixed with https://github.com/jc9108/ttv-favorites/commit/2be938dfbe16430f61ae4d044ac8300a01ebba74. please wait for cws to release the new version

**Closed by jc9108** 2022-11-11 00:33 UTC

**Comment by jc9108** [comment] 2022-11-11 23:49
![image](https://user-images.githubusercontent.com/31039318/201445206-4e941ab0-cabb-4c3c-8267-55dfa2b866db.png)

someone said it is still broken for them, even after the patch was released on cws. can you confirm if it was fixed or not for you? @hiccups1980 @IZeeLikeEyeZee

**Comment by hiccups1980** [comment] 2022-11-11 23:55
I can confirm it is working for me. 
![image](https://user-images.githubusercontent.com/5673109/201445646-6ece4ae6-3f0a-4d29-9d4e-abf4c13e844e.png)

**Comment by IZeeLikeEyeZee** [comment] 2022-11-12 22:03
@jc9108 working for me, but I had to update the extension manually. auto update is probably not gonna be instant for everyone, so that person is probably still on the old one

**Comment by Tomahoop** [comment] 2022-11-13 12:47
After trying different accounts and browsers I've determined that the issue is related to my Twitch account in some way. The extension works on Chrome if I use any Twitch account other than my main and this persists across browsers, which has left me very confused. My main twitch account doesn't have the feature to sort live streamers by recommended instead of just viewercount (which my other accounts do) if that matters.
